[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#0F172A"
font = "sans serif"

[server]
maxUploadSize = 200
headless = true